# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peti/projs/MKUltra-merged

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peti/projs/MKUltra-merged

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peti/projs/MKUltra-merged/CMakeFiles /home/peti/projs/MKUltra-merged//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peti/projs/MKUltra-merged/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mkultra

# Build rule for target.
mkultra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mkultra
.PHONY : mkultra

# fast build rule for target.
mkultra/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/build
.PHONY : mkultra/fast

#=============================================================================
# Target rules for targets named mkultra_autogen

# Build rule for target.
mkultra_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mkultra_autogen
.PHONY : mkultra_autogen

# fast build rule for target.
mkultra_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra_autogen.dir/build.make CMakeFiles/mkultra_autogen.dir/build
.PHONY : mkultra_autogen/fast

mkultra_autogen/mocs_compilation.o: mkultra_autogen/mocs_compilation.cpp.o
.PHONY : mkultra_autogen/mocs_compilation.o

# target to build an object file
mkultra_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/mkultra_autogen/mocs_compilation.cpp.o
.PHONY : mkultra_autogen/mocs_compilation.cpp.o

mkultra_autogen/mocs_compilation.i: mkultra_autogen/mocs_compilation.cpp.i
.PHONY : mkultra_autogen/mocs_compilation.i

# target to preprocess a source file
mkultra_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/mkultra_autogen/mocs_compilation.cpp.i
.PHONY : mkultra_autogen/mocs_compilation.cpp.i

mkultra_autogen/mocs_compilation.s: mkultra_autogen/mocs_compilation.cpp.s
.PHONY : mkultra_autogen/mocs_compilation.s

# target to generate assembly for a file
mkultra_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/mkultra_autogen/mocs_compilation.cpp.s
.PHONY : mkultra_autogen/mocs_compilation.cpp.s

src/gcode_writer.o: src/gcode_writer.cpp.o
.PHONY : src/gcode_writer.o

# target to build an object file
src/gcode_writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gcode_writer.cpp.o
.PHONY : src/gcode_writer.cpp.o

src/gcode_writer.i: src/gcode_writer.cpp.i
.PHONY : src/gcode_writer.i

# target to preprocess a source file
src/gcode_writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gcode_writer.cpp.i
.PHONY : src/gcode_writer.cpp.i

src/gcode_writer.s: src/gcode_writer.cpp.s
.PHONY : src/gcode_writer.s

# target to generate assembly for a file
src/gcode_writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gcode_writer.cpp.s
.PHONY : src/gcode_writer.cpp.s

src/gui/main.o: src/gui/main.cpp.o
.PHONY : src/gui/main.o

# target to build an object file
src/gui/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main.cpp.o
.PHONY : src/gui/main.cpp.o

src/gui/main.i: src/gui/main.cpp.i
.PHONY : src/gui/main.i

# target to preprocess a source file
src/gui/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main.cpp.i
.PHONY : src/gui/main.cpp.i

src/gui/main.s: src/gui/main.cpp.s
.PHONY : src/gui/main.s

# target to generate assembly for a file
src/gui/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main.cpp.s
.PHONY : src/gui/main.cpp.s

src/gui/main_window.o: src/gui/main_window.cpp.o
.PHONY : src/gui/main_window.o

# target to build an object file
src/gui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main_window.cpp.o
.PHONY : src/gui/main_window.cpp.o

src/gui/main_window.i: src/gui/main_window.cpp.i
.PHONY : src/gui/main_window.i

# target to preprocess a source file
src/gui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main_window.cpp.i
.PHONY : src/gui/main_window.cpp.i

src/gui/main_window.s: src/gui/main_window.cpp.s
.PHONY : src/gui/main_window.s

# target to generate assembly for a file
src/gui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/main_window.cpp.s
.PHONY : src/gui/main_window.cpp.s

src/gui/widgets/camera.o: src/gui/widgets/camera.cpp.o
.PHONY : src/gui/widgets/camera.o

# target to build an object file
src/gui/widgets/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/camera.cpp.o
.PHONY : src/gui/widgets/camera.cpp.o

src/gui/widgets/camera.i: src/gui/widgets/camera.cpp.i
.PHONY : src/gui/widgets/camera.i

# target to preprocess a source file
src/gui/widgets/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/camera.cpp.i
.PHONY : src/gui/widgets/camera.cpp.i

src/gui/widgets/camera.s: src/gui/widgets/camera.cpp.s
.PHONY : src/gui/widgets/camera.s

# target to generate assembly for a file
src/gui/widgets/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/camera.cpp.s
.PHONY : src/gui/widgets/camera.cpp.s

src/gui/widgets/mesh_3D_widget.o: src/gui/widgets/mesh_3D_widget.cpp.o
.PHONY : src/gui/widgets/mesh_3D_widget.o

# target to build an object file
src/gui/widgets/mesh_3D_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/mesh_3D_widget.cpp.o
.PHONY : src/gui/widgets/mesh_3D_widget.cpp.o

src/gui/widgets/mesh_3D_widget.i: src/gui/widgets/mesh_3D_widget.cpp.i
.PHONY : src/gui/widgets/mesh_3D_widget.i

# target to preprocess a source file
src/gui/widgets/mesh_3D_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/mesh_3D_widget.cpp.i
.PHONY : src/gui/widgets/mesh_3D_widget.cpp.i

src/gui/widgets/mesh_3D_widget.s: src/gui/widgets/mesh_3D_widget.cpp.s
.PHONY : src/gui/widgets/mesh_3D_widget.s

# target to generate assembly for a file
src/gui/widgets/mesh_3D_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/mesh_3D_widget.cpp.s
.PHONY : src/gui/widgets/mesh_3D_widget.cpp.s

src/gui/widgets/poly_2D_widget.o: src/gui/widgets/poly_2D_widget.cpp.o
.PHONY : src/gui/widgets/poly_2D_widget.o

# target to build an object file
src/gui/widgets/poly_2D_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_2D_widget.cpp.o
.PHONY : src/gui/widgets/poly_2D_widget.cpp.o

src/gui/widgets/poly_2D_widget.i: src/gui/widgets/poly_2D_widget.cpp.i
.PHONY : src/gui/widgets/poly_2D_widget.i

# target to preprocess a source file
src/gui/widgets/poly_2D_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_2D_widget.cpp.i
.PHONY : src/gui/widgets/poly_2D_widget.cpp.i

src/gui/widgets/poly_2D_widget.s: src/gui/widgets/poly_2D_widget.cpp.s
.PHONY : src/gui/widgets/poly_2D_widget.s

# target to generate assembly for a file
src/gui/widgets/poly_2D_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_2D_widget.cpp.s
.PHONY : src/gui/widgets/poly_2D_widget.cpp.s

src/gui/widgets/poly_3D_widget.o: src/gui/widgets/poly_3D_widget.cpp.o
.PHONY : src/gui/widgets/poly_3D_widget.o

# target to build an object file
src/gui/widgets/poly_3D_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_3D_widget.cpp.o
.PHONY : src/gui/widgets/poly_3D_widget.cpp.o

src/gui/widgets/poly_3D_widget.i: src/gui/widgets/poly_3D_widget.cpp.i
.PHONY : src/gui/widgets/poly_3D_widget.i

# target to preprocess a source file
src/gui/widgets/poly_3D_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_3D_widget.cpp.i
.PHONY : src/gui/widgets/poly_3D_widget.cpp.i

src/gui/widgets/poly_3D_widget.s: src/gui/widgets/poly_3D_widget.cpp.s
.PHONY : src/gui/widgets/poly_3D_widget.s

# target to generate assembly for a file
src/gui/widgets/poly_3D_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/gui/widgets/poly_3D_widget.cpp.s
.PHONY : src/gui/widgets/poly_3D_widget.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/slicer/generators/gentools/interval.o: src/slicer/generators/gentools/interval.cpp.o
.PHONY : src/slicer/generators/gentools/interval.o

# target to build an object file
src/slicer/generators/gentools/interval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/interval.cpp.o
.PHONY : src/slicer/generators/gentools/interval.cpp.o

src/slicer/generators/gentools/interval.i: src/slicer/generators/gentools/interval.cpp.i
.PHONY : src/slicer/generators/gentools/interval.i

# target to preprocess a source file
src/slicer/generators/gentools/interval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/interval.cpp.i
.PHONY : src/slicer/generators/gentools/interval.cpp.i

src/slicer/generators/gentools/interval.s: src/slicer/generators/gentools/interval.cpp.s
.PHONY : src/slicer/generators/gentools/interval.s

# target to generate assembly for a file
src/slicer/generators/gentools/interval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/interval.cpp.s
.PHONY : src/slicer/generators/gentools/interval.cpp.s

src/slicer/generators/gentools/plane.o: src/slicer/generators/gentools/plane.cpp.o
.PHONY : src/slicer/generators/gentools/plane.o

# target to build an object file
src/slicer/generators/gentools/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/plane.cpp.o
.PHONY : src/slicer/generators/gentools/plane.cpp.o

src/slicer/generators/gentools/plane.i: src/slicer/generators/gentools/plane.cpp.i
.PHONY : src/slicer/generators/gentools/plane.i

# target to preprocess a source file
src/slicer/generators/gentools/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/plane.cpp.i
.PHONY : src/slicer/generators/gentools/plane.cpp.i

src/slicer/generators/gentools/plane.s: src/slicer/generators/gentools/plane.cpp.s
.PHONY : src/slicer/generators/gentools/plane.s

# target to generate assembly for a file
src/slicer/generators/gentools/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/plane.cpp.s
.PHONY : src/slicer/generators/gentools/plane.cpp.s

src/slicer/generators/gentools/polylines.o: src/slicer/generators/gentools/polylines.cpp.o
.PHONY : src/slicer/generators/gentools/polylines.o

# target to build an object file
src/slicer/generators/gentools/polylines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/polylines.cpp.o
.PHONY : src/slicer/generators/gentools/polylines.cpp.o

src/slicer/generators/gentools/polylines.i: src/slicer/generators/gentools/polylines.cpp.i
.PHONY : src/slicer/generators/gentools/polylines.i

# target to preprocess a source file
src/slicer/generators/gentools/polylines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/polylines.cpp.i
.PHONY : src/slicer/generators/gentools/polylines.cpp.i

src/slicer/generators/gentools/polylines.s: src/slicer/generators/gentools/polylines.cpp.s
.PHONY : src/slicer/generators/gentools/polylines.s

# target to generate assembly for a file
src/slicer/generators/gentools/polylines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/polylines.cpp.s
.PHONY : src/slicer/generators/gentools/polylines.cpp.s

src/slicer/generators/gentools/section_organiser.o: src/slicer/generators/gentools/section_organiser.cpp.o
.PHONY : src/slicer/generators/gentools/section_organiser.o

# target to build an object file
src/slicer/generators/gentools/section_organiser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/section_organiser.cpp.o
.PHONY : src/slicer/generators/gentools/section_organiser.cpp.o

src/slicer/generators/gentools/section_organiser.i: src/slicer/generators/gentools/section_organiser.cpp.i
.PHONY : src/slicer/generators/gentools/section_organiser.i

# target to preprocess a source file
src/slicer/generators/gentools/section_organiser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/section_organiser.cpp.i
.PHONY : src/slicer/generators/gentools/section_organiser.cpp.i

src/slicer/generators/gentools/section_organiser.s: src/slicer/generators/gentools/section_organiser.cpp.s
.PHONY : src/slicer/generators/gentools/section_organiser.s

# target to generate assembly for a file
src/slicer/generators/gentools/section_organiser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/section_organiser.cpp.s
.PHONY : src/slicer/generators/gentools/section_organiser.cpp.s

src/slicer/generators/gentools/support_column_template.o: src/slicer/generators/gentools/support_column_template.cpp.o
.PHONY : src/slicer/generators/gentools/support_column_template.o

# target to build an object file
src/slicer/generators/gentools/support_column_template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/support_column_template.cpp.o
.PHONY : src/slicer/generators/gentools/support_column_template.cpp.o

src/slicer/generators/gentools/support_column_template.i: src/slicer/generators/gentools/support_column_template.cpp.i
.PHONY : src/slicer/generators/gentools/support_column_template.i

# target to preprocess a source file
src/slicer/generators/gentools/support_column_template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/support_column_template.cpp.i
.PHONY : src/slicer/generators/gentools/support_column_template.cpp.i

src/slicer/generators/gentools/support_column_template.s: src/slicer/generators/gentools/support_column_template.cpp.s
.PHONY : src/slicer/generators/gentools/support_column_template.s

# target to generate assembly for a file
src/slicer/generators/gentools/support_column_template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/gentools/support_column_template.cpp.s
.PHONY : src/slicer/generators/gentools/support_column_template.cpp.s

src/slicer/generators/infill_generator.o: src/slicer/generators/infill_generator.cpp.o
.PHONY : src/slicer/generators/infill_generator.o

# target to build an object file
src/slicer/generators/infill_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/infill_generator.cpp.o
.PHONY : src/slicer/generators/infill_generator.cpp.o

src/slicer/generators/infill_generator.i: src/slicer/generators/infill_generator.cpp.i
.PHONY : src/slicer/generators/infill_generator.i

# target to preprocess a source file
src/slicer/generators/infill_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/infill_generator.cpp.i
.PHONY : src/slicer/generators/infill_generator.cpp.i

src/slicer/generators/infill_generator.s: src/slicer/generators/infill_generator.cpp.s
.PHONY : src/slicer/generators/infill_generator.s

# target to generate assembly for a file
src/slicer/generators/infill_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/infill_generator.cpp.s
.PHONY : src/slicer/generators/infill_generator.cpp.s

src/slicer/generators/inner_shell_generator.o: src/slicer/generators/inner_shell_generator.cpp.o
.PHONY : src/slicer/generators/inner_shell_generator.o

# target to build an object file
src/slicer/generators/inner_shell_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/inner_shell_generator.cpp.o
.PHONY : src/slicer/generators/inner_shell_generator.cpp.o

src/slicer/generators/inner_shell_generator.i: src/slicer/generators/inner_shell_generator.cpp.i
.PHONY : src/slicer/generators/inner_shell_generator.i

# target to preprocess a source file
src/slicer/generators/inner_shell_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/inner_shell_generator.cpp.i
.PHONY : src/slicer/generators/inner_shell_generator.cpp.i

src/slicer/generators/inner_shell_generator.s: src/slicer/generators/inner_shell_generator.cpp.s
.PHONY : src/slicer/generators/inner_shell_generator.s

# target to generate assembly for a file
src/slicer/generators/inner_shell_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/inner_shell_generator.cpp.s
.PHONY : src/slicer/generators/inner_shell_generator.cpp.s

src/slicer/generators/outer_shell_generator.o: src/slicer/generators/outer_shell_generator.cpp.o
.PHONY : src/slicer/generators/outer_shell_generator.o

# target to build an object file
src/slicer/generators/outer_shell_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/outer_shell_generator.cpp.o
.PHONY : src/slicer/generators/outer_shell_generator.cpp.o

src/slicer/generators/outer_shell_generator.i: src/slicer/generators/outer_shell_generator.cpp.i
.PHONY : src/slicer/generators/outer_shell_generator.i

# target to preprocess a source file
src/slicer/generators/outer_shell_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/outer_shell_generator.cpp.i
.PHONY : src/slicer/generators/outer_shell_generator.cpp.i

src/slicer/generators/outer_shell_generator.s: src/slicer/generators/outer_shell_generator.cpp.s
.PHONY : src/slicer/generators/outer_shell_generator.s

# target to generate assembly for a file
src/slicer/generators/outer_shell_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/outer_shell_generator.cpp.s
.PHONY : src/slicer/generators/outer_shell_generator.cpp.s

src/slicer/generators/support_structure_generator.o: src/slicer/generators/support_structure_generator.cpp.o
.PHONY : src/slicer/generators/support_structure_generator.o

# target to build an object file
src/slicer/generators/support_structure_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/support_structure_generator.cpp.o
.PHONY : src/slicer/generators/support_structure_generator.cpp.o

src/slicer/generators/support_structure_generator.i: src/slicer/generators/support_structure_generator.cpp.i
.PHONY : src/slicer/generators/support_structure_generator.i

# target to preprocess a source file
src/slicer/generators/support_structure_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/support_structure_generator.cpp.i
.PHONY : src/slicer/generators/support_structure_generator.cpp.i

src/slicer/generators/support_structure_generator.s: src/slicer/generators/support_structure_generator.cpp.s
.PHONY : src/slicer/generators/support_structure_generator.s

# target to generate assembly for a file
src/slicer/generators/support_structure_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/generators/support_structure_generator.cpp.s
.PHONY : src/slicer/generators/support_structure_generator.cpp.s

src/slicer/global/dual_num.o: src/slicer/global/dual_num.cpp.o
.PHONY : src/slicer/global/dual_num.o

# target to build an object file
src/slicer/global/dual_num.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/dual_num.cpp.o
.PHONY : src/slicer/global/dual_num.cpp.o

src/slicer/global/dual_num.i: src/slicer/global/dual_num.cpp.i
.PHONY : src/slicer/global/dual_num.i

# target to preprocess a source file
src/slicer/global/dual_num.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/dual_num.cpp.i
.PHONY : src/slicer/global/dual_num.cpp.i

src/slicer/global/dual_num.s: src/slicer/global/dual_num.cpp.s
.PHONY : src/slicer/global/dual_num.s

# target to generate assembly for a file
src/slicer/global/dual_num.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/dual_num.cpp.s
.PHONY : src/slicer/global/dual_num.cpp.s

src/slicer/global/section.o: src/slicer/global/section.cpp.o
.PHONY : src/slicer/global/section.o

# target to build an object file
src/slicer/global/section.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/section.cpp.o
.PHONY : src/slicer/global/section.cpp.o

src/slicer/global/section.i: src/slicer/global/section.cpp.i
.PHONY : src/slicer/global/section.i

# target to preprocess a source file
src/slicer/global/section.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/section.cpp.i
.PHONY : src/slicer/global/section.cpp.i

src/slicer/global/section.s: src/slicer/global/section.cpp.s
.PHONY : src/slicer/global/section.s

# target to generate assembly for a file
src/slicer/global/section.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/global/section.cpp.s
.PHONY : src/slicer/global/section.cpp.s

src/slicer/object/RBF/FunctionCreator.o: src/slicer/object/RBF/FunctionCreator.cpp.o
.PHONY : src/slicer/object/RBF/FunctionCreator.o

# target to build an object file
src/slicer/object/RBF/FunctionCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/FunctionCreator.cpp.o
.PHONY : src/slicer/object/RBF/FunctionCreator.cpp.o

src/slicer/object/RBF/FunctionCreator.i: src/slicer/object/RBF/FunctionCreator.cpp.i
.PHONY : src/slicer/object/RBF/FunctionCreator.i

# target to preprocess a source file
src/slicer/object/RBF/FunctionCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/FunctionCreator.cpp.i
.PHONY : src/slicer/object/RBF/FunctionCreator.cpp.i

src/slicer/object/RBF/FunctionCreator.s: src/slicer/object/RBF/FunctionCreator.cpp.s
.PHONY : src/slicer/object/RBF/FunctionCreator.s

# target to generate assembly for a file
src/slicer/object/RBF/FunctionCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/FunctionCreator.cpp.s
.PHONY : src/slicer/object/RBF/FunctionCreator.cpp.s

src/slicer/object/RBF/NormalCreator.o: src/slicer/object/RBF/NormalCreator.cpp.o
.PHONY : src/slicer/object/RBF/NormalCreator.o

# target to build an object file
src/slicer/object/RBF/NormalCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/NormalCreator.cpp.o
.PHONY : src/slicer/object/RBF/NormalCreator.cpp.o

src/slicer/object/RBF/NormalCreator.i: src/slicer/object/RBF/NormalCreator.cpp.i
.PHONY : src/slicer/object/RBF/NormalCreator.i

# target to preprocess a source file
src/slicer/object/RBF/NormalCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/NormalCreator.cpp.i
.PHONY : src/slicer/object/RBF/NormalCreator.cpp.i

src/slicer/object/RBF/NormalCreator.s: src/slicer/object/RBF/NormalCreator.cpp.s
.PHONY : src/slicer/object/RBF/NormalCreator.s

# target to generate assembly for a file
src/slicer/object/RBF/NormalCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/RBF/NormalCreator.cpp.s
.PHONY : src/slicer/object/RBF/NormalCreator.cpp.s

src/slicer/object/bounding_box.o: src/slicer/object/bounding_box.cpp.o
.PHONY : src/slicer/object/bounding_box.o

# target to build an object file
src/slicer/object/bounding_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/bounding_box.cpp.o
.PHONY : src/slicer/object/bounding_box.cpp.o

src/slicer/object/bounding_box.i: src/slicer/object/bounding_box.cpp.i
.PHONY : src/slicer/object/bounding_box.i

# target to preprocess a source file
src/slicer/object/bounding_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/bounding_box.cpp.i
.PHONY : src/slicer/object/bounding_box.cpp.i

src/slicer/object/bounding_box.s: src/slicer/object/bounding_box.cpp.s
.PHONY : src/slicer/object/bounding_box.s

# target to generate assembly for a file
src/slicer/object/bounding_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/object/bounding_box.cpp.s
.PHONY : src/slicer/object/bounding_box.cpp.s

src/slicer/printable_object.o: src/slicer/printable_object.cpp.o
.PHONY : src/slicer/printable_object.o

# target to build an object file
src/slicer/printable_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/printable_object.cpp.o
.PHONY : src/slicer/printable_object.cpp.o

src/slicer/printable_object.i: src/slicer/printable_object.cpp.i
.PHONY : src/slicer/printable_object.i

# target to preprocess a source file
src/slicer/printable_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/printable_object.cpp.i
.PHONY : src/slicer/printable_object.cpp.i

src/slicer/printable_object.s: src/slicer/printable_object.cpp.s
.PHONY : src/slicer/printable_object.s

# target to generate assembly for a file
src/slicer/printable_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/printable_object.cpp.s
.PHONY : src/slicer/printable_object.cpp.s

src/slicer/slicer_module.o: src/slicer/slicer_module.cpp.o
.PHONY : src/slicer/slicer_module.o

# target to build an object file
src/slicer/slicer_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/slicer_module.cpp.o
.PHONY : src/slicer/slicer_module.cpp.o

src/slicer/slicer_module.i: src/slicer/slicer_module.cpp.i
.PHONY : src/slicer/slicer_module.i

# target to preprocess a source file
src/slicer/slicer_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/slicer_module.cpp.i
.PHONY : src/slicer/slicer_module.cpp.i

src/slicer/slicer_module.s: src/slicer/slicer_module.cpp.s
.PHONY : src/slicer/slicer_module.s

# target to generate assembly for a file
src/slicer/slicer_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkultra.dir/build.make CMakeFiles/mkultra.dir/src/slicer/slicer_module.cpp.s
.PHONY : src/slicer/slicer_module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mkultra_autogen"
	@echo "... mkultra"
	@echo "... mkultra_autogen/mocs_compilation.o"
	@echo "... mkultra_autogen/mocs_compilation.i"
	@echo "... mkultra_autogen/mocs_compilation.s"
	@echo "... src/gcode_writer.o"
	@echo "... src/gcode_writer.i"
	@echo "... src/gcode_writer.s"
	@echo "... src/gui/main.o"
	@echo "... src/gui/main.i"
	@echo "... src/gui/main.s"
	@echo "... src/gui/main_window.o"
	@echo "... src/gui/main_window.i"
	@echo "... src/gui/main_window.s"
	@echo "... src/gui/widgets/camera.o"
	@echo "... src/gui/widgets/camera.i"
	@echo "... src/gui/widgets/camera.s"
	@echo "... src/gui/widgets/mesh_3D_widget.o"
	@echo "... src/gui/widgets/mesh_3D_widget.i"
	@echo "... src/gui/widgets/mesh_3D_widget.s"
	@echo "... src/gui/widgets/poly_2D_widget.o"
	@echo "... src/gui/widgets/poly_2D_widget.i"
	@echo "... src/gui/widgets/poly_2D_widget.s"
	@echo "... src/gui/widgets/poly_3D_widget.o"
	@echo "... src/gui/widgets/poly_3D_widget.i"
	@echo "... src/gui/widgets/poly_3D_widget.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/slicer/generators/gentools/interval.o"
	@echo "... src/slicer/generators/gentools/interval.i"
	@echo "... src/slicer/generators/gentools/interval.s"
	@echo "... src/slicer/generators/gentools/plane.o"
	@echo "... src/slicer/generators/gentools/plane.i"
	@echo "... src/slicer/generators/gentools/plane.s"
	@echo "... src/slicer/generators/gentools/polylines.o"
	@echo "... src/slicer/generators/gentools/polylines.i"
	@echo "... src/slicer/generators/gentools/polylines.s"
	@echo "... src/slicer/generators/gentools/section_organiser.o"
	@echo "... src/slicer/generators/gentools/section_organiser.i"
	@echo "... src/slicer/generators/gentools/section_organiser.s"
	@echo "... src/slicer/generators/gentools/support_column_template.o"
	@echo "... src/slicer/generators/gentools/support_column_template.i"
	@echo "... src/slicer/generators/gentools/support_column_template.s"
	@echo "... src/slicer/generators/infill_generator.o"
	@echo "... src/slicer/generators/infill_generator.i"
	@echo "... src/slicer/generators/infill_generator.s"
	@echo "... src/slicer/generators/inner_shell_generator.o"
	@echo "... src/slicer/generators/inner_shell_generator.i"
	@echo "... src/slicer/generators/inner_shell_generator.s"
	@echo "... src/slicer/generators/outer_shell_generator.o"
	@echo "... src/slicer/generators/outer_shell_generator.i"
	@echo "... src/slicer/generators/outer_shell_generator.s"
	@echo "... src/slicer/generators/support_structure_generator.o"
	@echo "... src/slicer/generators/support_structure_generator.i"
	@echo "... src/slicer/generators/support_structure_generator.s"
	@echo "... src/slicer/global/dual_num.o"
	@echo "... src/slicer/global/dual_num.i"
	@echo "... src/slicer/global/dual_num.s"
	@echo "... src/slicer/global/section.o"
	@echo "... src/slicer/global/section.i"
	@echo "... src/slicer/global/section.s"
	@echo "... src/slicer/object/RBF/FunctionCreator.o"
	@echo "... src/slicer/object/RBF/FunctionCreator.i"
	@echo "... src/slicer/object/RBF/FunctionCreator.s"
	@echo "... src/slicer/object/RBF/NormalCreator.o"
	@echo "... src/slicer/object/RBF/NormalCreator.i"
	@echo "... src/slicer/object/RBF/NormalCreator.s"
	@echo "... src/slicer/object/bounding_box.o"
	@echo "... src/slicer/object/bounding_box.i"
	@echo "... src/slicer/object/bounding_box.s"
	@echo "... src/slicer/printable_object.o"
	@echo "... src/slicer/printable_object.i"
	@echo "... src/slicer/printable_object.s"
	@echo "... src/slicer/slicer_module.o"
	@echo "... src/slicer/slicer_module.i"
	@echo "... src/slicer/slicer_module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

